__version__: str

class Topology:
    def __init__(self, names: list[str], dependencies: list[list[int]]) -> None: ...
    def order(self) -> list[int]: ...
    def select(self, targets: list[str]) -> list[bool]: ...
    def start(self, targets: list[str], capacity: int) -> RunState: ...

class RunState:
    def admit(self) -> list[int]: ...
    def finish(self, node: int, outcome: str) -> None: ...
    def cancel(self) -> None: ...
    def done(self) -> bool: ...
    def states(self) -> list[str]: ...
