[package]
name = "traversal-python"
description = "Internal PyO3 bindings for Traversal"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lib]
name = "_native"
crate-type = ["cdylib"]
test = false
doctest = false

[dependencies]
traversal-core.workspace = true
pyo3.workspace = true
